version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - gosec
    - unconvert
    - unparam
    - prealloc
    - copyloopvar

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow

  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: unexported-return
        severity: warning

  gosec:
    excludes:
      - G104

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    - path: vendor/
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0
